- .githooks/post-merge
- .gitignore
- CHANGELOG.md
- config/checkstyle/checkstyle.gradle
- src/main/resources/version.properties
이번 PR은 이전 PR에서 누락된 폴더 및 설명을 추가하여 프로젝트 폴더 구조를 완성하는 목적입니다.
이전 커밋에서 빠졌던 내용을 보완하고, 폴더 구조를 정리하여 팀원들이 쉽게 활용할 수 있도록 수정했습니다.
이전 PR에서 누락된 폴더 및 구조 반영
.gitignore 내용 추가
프로젝트 폴더 구조가 정상적으로 생성되었는지 확인
.gitignore 적용이 잘 되었는지 확인
팀원들이 폴더를 쉽게 이해할 수 있도록 구조를 점검
> chore: Add missing files and updates from previous commit

- .gitignore
<type>([scope]): <commit message>
.gitignore file에 application-secret.properties 추가.
앞으로 민감한 정보는 application-secret.properties에 넣어서 관리하면 됩니다.
> chore(gitignore): update .gitignore file

- src/main/java/store/warab/controller/AuthController.java
로그아웃 기능 구현 
- Resolves #1 ]
1. 로그아웃 POST 요청 시 쿠키 만료
> feat: 로그아웃 후 쿠키 만료 구현

- src/main/java/store/warab/controller/CategoryController.java
- src/main/java/store/warab/controller/CommentController.java
- src/main/java/store/warab/controller/UserController.java
- src/main/java/store/warab/entity/Comment.java
- src/main/resources/version.properties
fix: api 응답 형식을 명세서에 맞게 수정
Description
api 명세서 시트와 응답형식이 맞지 않아 프론트에서 data를 뽑아오기 힘들 것 같아 controller에서 응답 형식을 수정했습니다.
> fix: api 응답 형식을 명세서에 맞게 수정

- src/main/java/store/warab/controller/CommentController.java
- src/main/java/store/warab/controller/GameController.java
- src/main/java/store/warab/controller/UserController.java
- src/main/java/store/warab/dto/GameInfoDto.java
- src/main/java/store/warab/dto/GameSearchResponseDto.java
- src/main/java/store/warab/dto/MainPageResponseDto.java
- src/main/java/store/warab/repository/GameStaticRepository.java
- src/main/java/store/warab/service/GameService.java
feat: 인기게임, 할인게임 for mainPage
메인 페이지에서 쓸 인기, 할인 게임 10개씩 반환.
리펙토링 필요
> feat: 인기게임, 할인게임 for mainPage

- src/main/java/store/warab/controller/UserController.java
- src/main/java/store/warab/dto/UserProfileUpdateRequest.java
- src/main/java/store/warab/service/UserService.java
- src/main/resources/version.properties
> fix: updateProfile 명세서에 맞는 요청 받아 처리할 수 있도록 수정

- src/main/java/store/warab/controller/UserController.java
- src/main/java/store/warab/dto/UserProfileUpdateRequest.java
- src/main/java/store/warab/service/DiscordService.java
- src/main/java/store/warab/service/UserService.java
- src/main/resources/version.properties
디스코드 초대 링크 유효성 검사 로직 수정 
- Resolves #4 
1. 디스코드 초대 링크 유효성 검사
> 디스코드 초대 링크 유효성 검사 수정 

- src/main/java/store/warab/config/SecurityConfig.java
- src/main/java/store/warab/controller/GameController.java
- src/main/java/store/warab/dto/GameLowestPriceDto.java
- src/main/java/store/warab/service/GameService.java
- src/main/resources/version.properties
최저가 가격 가져올 수 있는 api
1. 최저가 조회 api 추가
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> feat(api): feature lowest-price create

- src/main/java/store/warab/controller/GameController.java
- src/main/java/store/warab/repository/GameStaticRepository.java
- src/main/java/store/warab/service/GameService.java
- src/main/resources/version.properties
game 필터링하는 api 쿼리문 수정
#14 
1. category id 제외하고 모든 값 필터링 적용
- ["query", "rating_min", "rating_max", "price_min", "price_max", "singleplay", "multiplay", "online_players_min", "online_players_max", "sort", "mode", "limit", "offset"]
2. 페이징 적용
> fix(api): game filtering logic 수정

- src/main/java/store/warab/config/SecurityConfig.java
- src/main/java/store/warab/controller/DevAuthController.java
postman 에서 localhost:8080/api/dev/login으로 POST 요청 보내면 tester계정 권한을 얻게 됩니다.
> tester 계정 jwt 발급 api 생성

- src/main/java/store/warab/repository/GameStaticRepository.java
- src/main/resources/version.properties
main 페이지에서 불러오는 api 쿼리와 불러오는 게임 수정
1. 필요없는 테이블 join 삭제
2. 쿼리문 수정해서 불러오는 게임 수정
> fix: main 페이지 조회 쿼리 수정

- src/main/java/store/warab/controller/GameController.java
- src/main/java/store/warab/repository/GameStaticRepository.java
- src/main/java/store/warab/service/GameService.java
Game 필터 category_ids 로직 수정
1. category_ids 로직 수정
> fix: Game 필터 [category_ids] 로직 수정

- src/main/java/store/warab/repository/GameStaticRepository.java
선호 카테고리 필터링 쿼리를 수정
1. 선호 카테고리 필터링을 id가 아닌 리뷰 순을 기준으로 정렬
> fix: 선호 카테고리 필터링 쿼리 수정

- src/main/java/store/warab/controller/DevAuthController.java
- src/main/java/store/warab/controller/GameController.java
- src/main/java/store/warab/repository/GameStaticRepository.java
- src/main/java/store/warab/service/GameService.java
- src/main/resources/version.properties
추천 필터링 적용 시 선호 카테고리에 속하는 게임 리스트 조회.
선호 카테고리 없는 경우 처리 어떻게 할지 논의 필요.
> fix: 추천 게임 필터링 추가

- src/main/java/store/warab/common/exception/GlobalExceptionHandler.java
- src/main/java/store/warab/config/SecurityConfig.java
- `AuthenticationEntryPoint`, `AccessDeniedHandler` 명시 등록
- 인증 실패 시 401, 인가 실패 시 403 JSON 응답 반환
- JWT 인증 실패 시 명확한 401 응답 반환 (`JWTFilter` 수정)
- 컨트롤러/서비스에서 발생한 예외를 처리하는 `@RestControllerAdvice` 보완
@RestControllerAdvice를 제외한 예외처리 필요
> fix: 인증된 요청에서 발생한 예외가 리다이렉트되는 문제 수정 (임시)

- build.gradle
- src/main/resources/version.properties
sentry 등록
추후 팀 계정을 만들어 sentry 정보를 secret에 등록하여 동적으로 바꿔줘야 합니다.
> feat: sentry 설정

- src/main/java/store/warab/controller/GameController.java
Closes #38
post맨으로 api요청을 보내면 5개이상 카테고리를 설정해도 보낼 수 있는 현상을 해결했습니다.
Closes #38 
1. GameController에서 요청을 받은 뒤 카테고리아이디가 5개가 넘으면 early return 하게 했습니다.
1. postman으로 요청을 보냈음
> fix(api): search filter categories select issue

- .github/workflows/deploy-common.yml
CI/CD를 위한 yml파일 수정
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> fix(cd): update deploy-common.yml

- .github/workflows/deploy-common.yml
- .github/workflows/deploy.yml
ci 수정
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> fix(cd): 오탈자 수정

- .github/workflows/deploy-common.yml
- src/main/java/store/warab/oauth2/CustomSuccessHandler.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> fix(api): cookie setting

- .github/workflows/deploy-common.yml
- src/main/java/store/warab/oauth2/CustomSuccessHandler.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> cookie test

- src/main/java/store/warab/oauth2/CustomSuccessHandler.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> fix(cookie): update set cookies

- .github/workflows/deploy-common.yml
- .github/workflows/deploy.yml
- src/main/resources/application.properties
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> [CD] change cd files

- src/main/java/store/warab/config/SecurityConfig.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> fix(logger): add log

- src/main/java/store/warab/oauth2/CustomSuccessHandler.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> fix(cookie): add option: sameSite

- src/main/java/store/warab/oauth2/CustomSuccessHandler.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> fix(cookie): update cookie

- .github/workflows/deploy-common.yml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> fix(cd): update baseUrl

- src/main/java/store/warab/oauth2/CustomSuccessHandler.java
> feat: flushBuffer

- src/main/resources/application.properties
application.properties에 
logging.level.org.springframework.security.oauth2.client=DEBUG
logging.level.org.springframework.security.oauth2.core=DEBUG
추가
> feat: security debug

- .github/workflows/deploy-common.yml
- build.gradle
- src/main/java/store/warab/config/SecurityConfig.java
- src/main/java/store/warab/controller/AuthController.java
- src/main/java/store/warab/oauth2/CustomSuccessHandler.java
- src/main/resources/log4j2-spring.xml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> change log system.

- src/main/java/store/warab/config/SecurityConfig.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> test(logs): jwt log tests

- src/main/java/store/warab/config/SecurityConfig.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> test(logging): Sentry test

- src/main/java/store/warab/config/SecurityConfig.java
- src/main/java/store/warab/service/CustomOAuth2UserService.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> test(logger): set logs

- .github/workflows/deploy-common.yml
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> fix(cd): self-hosted

- src/main/java/store/warab/oauth2/CustomSuccessHandler.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> fix(secure): set cookies

- src/main/java/store/warab/oauth2/CustomSuccessHandler.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> fix(cookie): update cookie setting

- src/main/java/store/warab/oauth2/CustomSuccessHandler.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> fix(auth): update customsuccesshandler

- src/main/java/store/warab/oauth2/CustomSuccessHandler.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> fix(cookie): cookie change

- src/main/java/store/warab/remove/OAuth2LoginAddLoggingFilter.java
- src/main/java/store/warab/remove/OAuth2LoginCallbackLoggingFilter.java
> add sentry logging

- src/main/java/store/warab/remove/OAuth2LoginAddLoggingFilter.java
> chore: 로깅 코드 수정

- src/main/java/store/warab/config/SecurityConfig.java
> chore: 세션 설정 변경

- src/main/java/store/warab/oauth2/CustomSuccessHandler.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> fix(cookie): change setHeader -> addHeader

- src/main/java/store/warab/config/SecurityConfig.java
> chore: release

- src/main/java/store/warab/controller/GameController.java
- src/main/java/store/warab/dto/GameCurrentPriceDto.java
- src/main/java/store/warab/dto/GameDiscountInfoDto.java
- src/main/java/store/warab/dto/PlatformDiscountInfoDto.java
- src/main/java/store/warab/entity/CurrentPriceByPlatform.java
- src/main/java/store/warab/entity/Platform.java
- src/main/java/store/warab/repository/CurrentPriceByPlatformRepository.java
- src/main/java/store/warab/repository/PlatformRepository.java
- src/main/java/store/warab/service/GameService.java
> feat: prices_by_platform

- src/main/java/store/warab/controller/GameController.java
- src/main/java/store/warab/dto/GameCurrentPriceDto.java
- src/main/java/store/warab/dto/LowestPriceLinkDto.java
- src/main/java/store/warab/service/GameService.java
> feat: get lowest_price_link

- src/main/java/store/warab/dto/GameVideoDto.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> fix(api): fixed typo

- src/main/resources/application.properties
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> fix(settings): add cookie domain

- src/main/java/store/warab/config/SecurityConfig.java
- src/main/java/store/warab/controller/CategoryController.java
- src/main/java/store/warab/controller/CommentController.java
- src/main/java/store/warab/controller/DevAuthController.java
- src/main/java/store/warab/controller/GameController.java
- src/main/java/store/warab/dto/CategoryResponseDto.java
- src/main/java/store/warab/dto/CommentResponseDto.java
- src/main/java/store/warab/dto/GameDetailResponseDto.java
- src/main/java/store/warab/dto/GameDiscountInfoDto.java
- src/main/java/store/warab/dto/GameInfoDto.java
- src/main/java/store/warab/dto/GameLowestPriceDto.java
- src/main/java/store/warab/dto/GameSearchResponseDto.java
- src/main/java/store/warab/dto/GameVideoDto.java
- src/main/java/store/warab/dto/LowestPriceLinkDto.java
- src/main/java/store/warab/dto/PlatformDiscountInfoDto.java
- src/main/java/store/warab/dto/UserProfileResponseDto.java
- src/main/java/store/warab/entity/GameDynamic.java
- src/main/java/store/warab/entity/GameStatic.java
- src/main/java/store/warab/entity/GameVideo.java
- src/main/java/store/warab/entity/Platform.java
- src/main/java/store/warab/entity/User.java
- src/main/java/store/warab/service/GameService.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> Refactoring

- src/main/java/store/warab/dto/CommentResponseDto.java
getter 어노테이션 추가하여 댓글 응답 정상 동작하도록 수정
> fix: 댓글 응답에 필요한 필드 직렬화 안되던 문제 해결

- src/main/java/store/warab/dto/CommentResponseDto.java
> fix: 응답에 맞게 댓글 dto 수정

- src/main/java/store/warab/controller/DiscordLinkController.java
> chore: 예외 처리 개선

- src/main/java/store/warab/service/GameService.java
일괄적으로 처리하던 추천 문구 카테고리 별로 수정 
1. 카테고리 별 추천 문구 적용
> feat: 카테고리 별 스타일 문구 적용

- src/main/java/store/warab/service/GameService.java
> fix: 카테고리 별 스타일 문구 수정
